version: '3.3'
services:
    run:
        image: aktosecurity/ebpf
        privileged: true
        volumes:
            - /lib/modules:/lib/modules:ro
            - /usr/src:/usr/src:ro
            - /sys:/sys:ro
            - /usr:/usr_host:ro
        network_mode: host
        env_file: ./ebpf.env